# Generated by Django 6.0.1 on 2026-02-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_alter_documento_options_documento_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
    ]
