# Generated by Django 6.0.1 on 2026-02-18 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_cliente_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True, verbose_name='Folio Fiscal (UUID)')),
                ('fecha_emision', models.DateTimeField()),
                ('rfc_emisor', models.CharField(max_length=13)),
                ('nombre_emisor', models.CharField(max_length=255)),
                ('rfc_receptor', models.CharField(max_length=13)),
                ('nombre_receptor', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('archivo_xml', models.FileField(upload_to='gastos/xml/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto / Factura',
                'verbose_name_plural': 'Gastos y Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
