# Generated by Django 6.0.1 on 2026-02-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_facturagasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='access_gastos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='access_qr',
            field=models.BooleanField(default=False),
        ),
    ]
